config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  #root :to => redirect("https://www.facebook.com/tallerpinon?fref=ts")

	get	'home' => 'static_pages#home'
	get	'help' => 'static_pages#help'
	get 'about' => 'static_pages#about'
	get 'customapp' => 'static_pages#customapp'
	post 'fetch_pieza' => 'static_pages#fetch_pieza'
	post 'save_changes' => 'static_pages#save_changes'
	post 'contact_create' => 'static_pages#contact_create'
	get 'tu_pinon' => 'static_pages#tu_pinon'
	get 'contact' => 'static_pages#contact'
	get 'signup' => 'users#new'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  
	resources :users do
    member do
      get :following, :followers
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :motos,               only: [:index, :new, :create, :destroy, :edit, :update, :show]
  get 'index_pinon' => 'motos#indexPinon'
  
  resources :custom_apps,          only: [:create, :destroy, :update, :index, :show, :index]
  post 'recarga' => 'custom_apps#recarga'

  get 'auth/:provider/callback', to: 'users#omniauth_listener'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :logged_in_user, only: [:share, :save_changes]

  def home
    if logged_in?
      @micropost = current_user.microposts.build 
      @feed_items = current_user.feed.paginate(page: params[:page],:per_page => 10) # feed declared in user model.
    end
    @userPinon = User.find_by(email: 'contacto@tallerpinon.cl') #userPinon para mostrar las motos piñon
    if !@userPinon.nil?  # I had to put this in order to pass the test 
      @motos = @userPinon.motos.paginate(page: params[:page],  :per_page => 2) 
    end
  end

  def customapp 
    @modelo = params[:modelo]
    gon.archivos 
    gon.update_path
    if logged_in?
      if current_user.custom_apps.any?
        @customapp = current_user.custom_apps
        
        if customapp_in?
          crea_gon_object(current_custom.est_per_file, current_custom.apl_per_file, current_custom.asi_per_file, current_custom.man_per_file, current_custom.lla_per_file, current_custom.foc_per_file, "custom_app/#{current_custom.modelo}/perspectiva/per_plantilla.png", @modelo) # crea objeto gon, con los datos de color de las partes de la moto => gon.archivos
          gon.update_path = custom_app_path(@customapp)  
        end
#        puts @customapp.est_lat_file
      end
    end
  end

  def tu_pinon
    @userPinon = User.find_by(email: 'contacto@tallerpinon.cl') 
    @motosPinon = @userPinon.motos.paginate(page: params[:page],  :per_page => 2) 
  end

  def share
    # To implement for record the data inside CustomApp
  end 
 

  def save_changes

    if logged_in?
     redirect_to customapp_path
    end

  end

  def fetch_pieza
    color =  params[:color]
    parte = params[:parte]
    modelo = params[:modelo]
    color = color.upcase
    @per_file = "custom_app/"+modelo+"/perspectiva/per_"+parte+"_"+color+".png"
    @lat_file = "custom_app/"+modelo+"/lateral/lat_"+parte+"_"+color+".png"
    @sup_file = "custom_app/"+modelo+"/superior/sup_"+parte+"_"+color+".png"
    per_r = ActionController::Base.helpers.asset_path @per_file
    lat_r = ActionController::Base.helpers.asset_path @lat_file
    sup_r = ActionController::Base.helpers.asset_path @sup_file 
    render :json => { :per => per_r, :lat => lat_r , :sup => sup_r } 
  end

  def help
  end

	def about
	end

	def contact
    @nombre = params[:name]
    @email = params[:email]
    @custom_id = params[:custom_id]
    @modelo = params[:modelo]
	end

  def contact_create
    @contacto = params[:contact]

#    ContactMailer.contact_form(@contacto).deliver
    ContactMailer.delay.contact_form(@contacto)
    flash[:info] = "Tu mensaje ha sido enviado!"
    redirect_to root_url
  end

  private

    def crea_gon_object(est, apl, asi, man, lla, foc, base, modelo)
      color_est = get_color_from_path est
      color_apl = get_color_from_path apl
      color_asi = get_color_from_path asi
      color_man = get_color_from_path man
      color_lla = get_color_from_path lla
      color_foc = get_color_from_path foc
      
      #archivos del estanque
          @est_pf = ActionController::Base.helpers.asset_path "custom_app/"+modelo.to_s+"/perspectiva/per_estanque_"+color_est.to_s+".png" 
          @est_lf = ActionController::Base.helpers.asset_path "custom_app/"+modelo.to_s+"/lateral/lat_estanque_"+color_est.to_s+".png"
          @est_sf = ActionController::Base.helpers.asset_path "custom_app/"+modelo.to_s+"/superior/sup_estanque_"+color_est.to_s+".png"
      #archivos de la aplicacion del estanque
          @apl_pf = ActionController::Base.helpers.asset_path "custom_app/"+modelo.to_s+"/perspectiva/per_aplicacion_"+color_apl.to_s+".png"
          @apl_lf = ActionController::Base.helpers.asset_path "custom_app/"+modelo.to_s+"/lateral/lat_aplicacion_"+color_apl.to_s+".png"
          @apl_sf = ActionController::Base.helpers.asset_path "custom_app/"+modelo.to_s+"/superior/sup_aplicacion_"+color_apl.to_s+".png"
      #archivos del asiento 
          @asi_pf = ActionController::Base.helpers.asset_path "custom_app/"+modelo.to_s+"/perspectiva/per_asiento_"+color_asi.to_s+".png"
          @asi_lf = ActionController::Base.helpers.asset_path "custom_app/"+modelo.to_s+"/lateral/lat_asiento_"+color_asi.to_s+".png"
          @asi_sf = ActionController::Base.helpers.asset_path "custom_app/"+modelo.to_s+"/superior/sup_asiento_"+color_asi.to_s+".png"
      #manillar
          @man_pf = ActionController::Base.helpers.asset_path "custom_app/"+modelo.to_s+"/perspectiva/per_manilla_"+color_man.to_s+".png" 
          @man_lf = ActionController::Base.helpers.asset_path "custom_app/"+modelo.to_s+"/lateral/lat_manilla_"+color_man.to_s+".png"
          @man_sf = ActionController::Base.helpers.asset_path "custom_app/"+modelo.to_s+"/superior/sup_manilla_"+color_man.to_s+".png"
      # llantas
          @lla_pf = ActionController::Base.helpers.asset_path "custom_app/"+modelo.to_s+"/perspectiva/per_llanta_"+color_lla.to_s+".png" 
          @lla_lf = ActionController::Base.helpers.asset_path "custom_app/"+modelo.to_s+"/lateral/lat_llanta_"+color_lla.to_s+".png"
          @lla_sf = ActionController::Base.helpers.asset_path "custom_app/"+modelo.to_s+"/superior/sup_llanta_"+color_lla.to_s+".png"
      # Focos
          @foc_pf = ActionController::Base.helpers.asset_path "custom_app/"+modelo.to_s+"/perspectiva/per_foco_"+color_foc.to_s+".png" 
          @foc_lf = ActionController::Base.helpers.asset_path "custom_app/"+modelo.to_s+"/lateral/lat_foco_"+color_foc.to_s+".png"
          @foc_sf = ActionController::Base.helpers.asset_path "custom_app/"+modelo.to_s+"/superior/sup_foco_"+color_foc.to_s+".png"
          
          gon.archivos = { est_pf: @est_pf, est_lf: @est_lf, est_sf: @est_sf,
                           apl_pf: @apl_pf, apl_lf: @apl_lf, apl_sf: @apl_sf,
                           asi_pf: @asi_pf, asi_lf: @asi_lf, asi_sf: @asi_sf,
                           man_pf: @man_pf, man_lf: @man_lf, man_sf: @man_sf, 
                           lla_pf: @lla_pf, lla_lf: @lla_lf, lla_sf: @lla_sf, 
                           foc_pf: @foc_pf, foc_lf: @foc_lf, foc_sf: @foc_sf} 
   end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
    def get_color_from_path (p)
      color_est = /(_)([0-9A-F])+/.match(p)
      color_est = /([0-9A-F])+/.match(color_est.to_s)
    end 
end

app/views/static_pages/_custombuttons.html.erb
<div class="container menu-custom"  style='background-color: #000; border-radius: 60px; height: 130px;'  >
  <div class="row">
    <div class="col-md-2 col-md-offset-2">
      <ul class="nav navbar-nav navbar-left">
          <li class="dropdown">
            <%= link_to image_tag('custom_app/est-icon.png', alt:'estanque icon', style:'max-width:100px; height:auto; '), '#', class:'dropdown-toogle btn-parte-moto', :data => {:toggle=>"dropdown"}%>
            <ul class="dropdown-menu">
              <li>
                <ul class='kwicks kwicks-horizontal'>
                  <% 19.times do |x| %>
                    <li id='panel-0<%=x%>'> </li> 
                  <% end %>
                </ul>
              </li>
            </ul>
          </li>

      </ul>
  </div>
    <div class="col-md-2">
    <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <%= link_to image_tag('custom_app/apl-icon.png', alt:'estanque icon', style:'max-width:100px; height:auto;'), '#', class:'dropdown-toogle  btn-parte-moto', :data => {:toggle=>"dropdown"}%>
            <ul class="dropdown-menu">
              <li>
                <ul class='kwicks kwicks-horizontal'>
                  <% 25.times do |x| %>
                    <li id='panel-1<%=x%>'> </li> 
                  <% end %>
                </ul>
              </li>
            </ul>
          </li>
    </ul>
  </div>
    <div class="col-md-2">
    <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <%= link_to image_tag('custom_app/asi-icon.png', alt:'estanque icon', style:'max-width:100px; height:auto;'), '#', class:'dropdown-toogle btn-parte-moto', :data => {:toggle=>"dropdown"}%>
            <ul class="dropdown-menu">
              <li>
                <ul class='kwicks kwicks-horizontal'>
                  <% 6.times do |x| %>
                    <li id='panel-2<%=x%>'> </li> 
                  <% end %>
                </ul>
              </li>
            </ul>
          </li>
    </ul>
  </div>
    <div class="col-md-2">
    <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <%= link_to image_tag('custom_app/man-icon.png', alt:'estanque icon', style:'max-width:100px; height:auto;'), '#', class:'dropdown-toogle btn-parte-moto', :data => {:toggle=>"dropdown"}%>
            <ul class="dropdown-menu">
              <li>
                <ul class='kwicks kwicks-horizontal'>
                  <% 7.times do |x| %>
                    <li id='panel-3<%=x%>'> </li> 
                  <% end %>
                </ul>
              </li>
            </ul>
          </li>
    </ul>
  </div>
  </div>
</div>

app/views/static_pages/_customdisplays.html.erb
<!-- DISPLAYS -->
<div class="row">
  <div class="col-md-8  ">
    <div class="plantilla-moto">
    <%= image_tag("custom_app/area_transparente.png", alt: "per-est-app", style:'max-width:100%; height:auto;', id:'per-est-app', class:'capa-moto' )%>
    <%= image_tag("custom_app/area_transparente.png", alt: "per-apl-app", style:'max-width:100%; height:auto;', id:'per-apl-app', class:'capa-moto' )%>
    <%= image_tag("custom_app/area_transparente.png", alt: "per-asi-app", style:'max-width:100%; height:auto;', id:'per-asi-app', class:'capa-moto' )%>
    <%= image_tag("custom_app/area_transparente.png", alt: "per-man-app", style:'max-width:100%; height:auto;', id:'per-man-app', class:'capa-moto' )%>
    <%= image_tag("custom_app/perspectiva/per_plantilla.png", alt: "per-pla-app", style:'max-width:100%; height:auto;', id:'per-pla-app', class:'capa-moto' )%>
    <%= image_tag("custom_app/area_transparente.png", alt: "test moto img", style:'max-width:100%; height:auto;', class:'capa-moto-ultima')%>
    </div>
  </div>
  <div class="col-md-4 ">
    <div class="row ">
      <div class="col-md-12">
        <div class="plantilla-moto">
    <%= image_tag("custom_app/area_transparente.png", alt: "sup-est-app", style:'max-width:100%; height:auto;', id:'sup-est-app', class:'capa-moto' )%>
    <%= image_tag("custom_app/area_transparente.png", alt: "sup-apl-app", style:'max-width:100%; height:auto;', id:'sup-apl-app', class:'capa-moto' )%>
    <%= image_tag("custom_app/area_transparente.png", alt: "sup-asi-app", style:'max-width:100%; height:auto;', id:'sup-asi-app', class:'capa-moto' )%>
    <%= image_tag("custom_app/area_transparente.png", alt: "sup-man-app", style:'max-width:100%; height:auto;', id:'sup-man-app', class:'capa-moto' )%>
    <%= image_tag("custom_app/superior/sup_plantilla.png", alt: "sup-pla-app", style:'max-width:100%; height:auto;', id:'sup-pla-app', class:'capa-moto' )%>
    <%= image_tag("custom_app/area_transparente.png", alt: "area transparente", style:'max-width:100%; height:auto;')%>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="plantilla-moto">
    <%= image_tag("custom_app/area_transparente.png", alt: "test moto img", style:'max-width:100%; height:auto;', id:'lat-est-app', class:'capa-moto' )%>
    <%= image_tag("custom_app/area_transparente.png", alt: "test moto img", style:'max-width:100%; height:auto;', id:'lat-apl-app', class:'capa-moto' )%>
    <%= image_tag("custom_app/area_transparente.png", alt: "test moto img", style:'max-width:100%; height:auto;', id:'lat-asi-app', class:'capa-moto' )%>
    <%= image_tag("custom_app/area_transparente.png", alt: "test moto img", style:'max-width:100%; height:auto;', id:'lat-man-app', class:'capa-moto' )%>
    <%= image_tag("custom_app/lateral/lat_plantilla.png", alt: "test moto img", style:'max-width:100%; height:auto;', id:'lat-pla-app', class:'capa-moto' )%>
    <%= image_tag("custom_app/area_transparente.png", alt: "test moto img", style:'max-width:100%; height:auto;')%>
        </div>
      </div>
    </div>
  </div>

</div>

  <p style='color:#101010;' class='center'> Presiona F11 para ver la aplicación en pantalla completa </p>

<%= javascript_tag do %>
  window.custompath = '<%= j custom_apps_url %>';
<% end %>

app/views/static_pages/_galeria_pinon.html.erb
<ul class='motos-preview' >
  <% if !@motos.nil? %> <!-- I had to put this to pass the test -->
    <%= render @motos %>
  <% end %>
</ul>

app/views/static_pages/_loginview.html.erb
 <!-- This is not been used -->
    <div class="row">
      <div class="col-md-4">
      <aside>
        <section class="user_info">
          <%= render 'shared/user_info' %>
        </section>
        <section class="stats">
          <%= render 'shared/stats' %>
        </section>
        <section class="micropost_form" %>
        <%= render 'shared/micropost_form' %>
        </section>
      </aside>
      </div>
      <div class="col-md-8">
        <h3> Comentarios </h3>
        <%= render 'shared/feed' %>
      </div>
    </div>

app/views/static_pages/_motopinon.html.erb
<li id="moto-<%= @moto.id %>" >
  <div class="row">
    <div class="col-md-9">
      <%= image_tag @moto.picture.url, class:'moto-responsive img-g' if @moto.picture? %>
    </div>

    <div class="col-md-3">
      <div class="row">
        <div class="col-md-12">
          <% user = User.find_by(id: @moto.user_id) %>
          <%= gravatar_for user, size: 50 %>
          <%= link_to user.name, user %>
        </div>
        <br>
        <div class="col-md-12">
          <h3 class="nombre text-lake-35px"> <%= @moto.name %></h3> <br>
          <span class="modelo"> modelo: <%= @moto.modelo %> </span> <br>
          <span > ano: <%= @moto.ano %> </span> <br>
          <span > cilindrada: <%= @moto.cilindrada %> </span> <br>

          <% if !@precio.blank? %>
            <h3 class="nombre text-lake-35px"> $ <%= @precio %></h3> <br>
          <% else %>
          </br>
          <% end %>
          <%= link_to "cotizar modelo", contact_path( :modelo => @modelo  )  ,  class:'btn btn-primary'%>
          <hr>
          <% if logged_in? && current_user.admin? && !current_user?(@moto.user_id) %>
            <%= link_to "editar moto", edit_moto_path(@moto)  %> <br>
            <%= link_to "eliminar", @moto, method: :delete, data: { confirm: "Estas seguro de eliminar esta moto?" } %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</li>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>


<div class="row">
  <% if customapp_in? && CustomApp.find_by(id: @custom_id) != nil %>
    <h1 class="titulo-mono">Cotización</h1>
    <div id="custom-moto-<%= @custom_id %>" class="col-md-6">
      <div class="plantilla-moto">
        <% img_url = CustomApp.find_by(id: @custom_id).picture.url %>
       <%= image_tag( img_url, alt: "imagen moto", style:'max-width:100%; height:auto;', id:'per-'+current_custom.id.to_s  )%>  
      </div>
    </div>
    <div class="col-md-6 ">
      <%= form_for(:contact, url: contact_create_path) do |f| %>

        <%= f.label 'Nombre' %>
        <%= f.text_field :name, class: 'form-control', value: @nombre %>
  
        <%= f.label 'Email'  %>
        <%= f.text_field :email, class: 'form-control', value: @email %>
  
        <%= f.label 'Asunto' %>
        <%= f.text_field :asunto, class: 'form-control', value: 'Cotización' %>

        <%= f.hidden_field :moto_cot, value: "#{Rails.root}"+custom_app_path(:id => current_custom.id) %>

        <%= f.label 'Modelo' %>
        <%= f.text_field :modelo, class: 'form-control', value: @modelo %>

        <%= f.label 'Mensaje' %>
        <%= f.text_area :message, class: 'form-control'%>
  
        <%= f.submit "Enviar", class: "btn btn-primary" %>
        <!--        <%= f.label 'Este formulario se enviará con el link respectivo de tu customización' %> -->
      <% end %>
  </div>
  <% else %>
    <% if !@modelo.nil? %>
      <h1 class="titulo-mono">Cotización</h1>
    <% else %>
      <h1 class="titulo-mono">Contacto</h1>
    <% end %>
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:contact, url: contact_create_path) do |f| %>

      <%= f.label 'Nombre' %>
      <%= f.text_field :name, class: 'form-control', value: @nombre %>

      <%= f.label 'Email'  %>
      <%= f.text_field :email, class: 'form-control' %>

      <% if !@modelo.nil? %>
        <%= f.label 'Modelo' %>
        <%= f.text_field :modelo, class: 'form-control', value: @modelo %>
        <%= f.label 'Asunto' %>
        <%= f.text_field :asunto, class: 'form-control', value: 'Cotización' %>
      <% else %>
        <%= f.label 'Asunto' %>
        <%= f.text_field :asunto, class: 'form-control' %>
      <% end %>

      <%= f.label 'Mensaje' %>
      <%= f.text_area :message, class: 'form-control'%>

      <%= f.submit "Enviar", class: "btn btn-primary" %>
    <% end %>

  </div>

  <% end %>

</div>

app/views/static_pages/customapp.html.erb
<!-- APLICACIÓN CUSTOMIZACIÓN -->
<% content_for :custom do %>
  <div class="container">
    <%= render 'static_pages/customapp_partials/custombuttons' %>
  </div>
<br>

<!-- Parciales con los dibujos de cada modelo -->
  <% modelo = true %>
  <div class="container">
  <% case @modelo %>
  <% when 'vizcacha' %>
    <%= render 'static_pages/customapp_partials/customdisplays_vizcacha' %>
  <% when 'jacana' %>
    <%= render 'static_pages/customapp_partials/customdisplays_jacana' %>
  <% else %>
    <% modelo = false %>
    <h2> Escoje el modelo a customizar: </h2>
      <div class="row">
        <div class="center col-md-8 col-md-offset-2" style="margin-top:0%;">
          <div class="col-md-4 col-md-offset-2">
            <%= link_to image_tag("custom_app/vizcacha_logo.png", size:'150x150'), customapp_path(:modelo => 'vizcacha'), method: :get %>
          </div> 
          <div class="col-md-4 ">
            <%= link_to image_tag("custom_app/jacana_logo.png", size:'150x150'), customapp_path(:modelo => 'jacana'), method: :get%>
          </div>
        </div>
      </div>
  <% end %>
  </div>
  
  <!-- imagen para cuando se esta cargando la imagen -->
  <div class="row" id="loading-indicator">
    <div class="col-xs-1 col-xs-offset-6">
      <%= image_tag("loading.gif", size:'30x30')%>
    </div>
    </br></br>
  </div>

  <!-- botones para guardar nuevo modelo o registrarse -->
  <div class="container">
    <% if modelo %>
    <%= render 'static_pages/customapp_partials/customlinks' %>
  <% end %>
  </div>
 
  <br>



<!-- visualizaciones de las customizaciones del usuario actual -->
  <% if logged_in? %>
    <div class="container">
      <%= render 'static_pages/customapp_partials/miscustoms' %>
    </div>
  <% end %>

<%= javascript_tag do %>
  window.custompath = '<%= j custom_apps_url %>'; 
  window.modelo = '<%= j @modelo %>';
<% end %>

<% end %>

app/views/static_pages/help.html.erb
  <% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://www.railstutorial.org/#help">Rails Tutorial help section</a>.
  To get help on this sample app, see the
  <a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
  book</a>.
</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<% content_for :home do %>

  <% if logged_in? %>
    <div class="container">
       <%= render 'shared/loginview' %>
    </div>
   <% else %>
    <!-- PRIMERA VENTANA INTRO - VIDEO/LOGO -->
    <div class="header-unit-0">
      <div id="video-container">
        <video autoplay loop muted class="fillWidth">
          <source src="https://s3-sa-east-1.amazonaws.com/pinon-images/videos/Spot_Taller_Pi_on_20_segundos_FULL_HD_FINAL_.mp4" type="video/mp4"/>
          <source src="https://s3-sa-east-1.amazonaws.com/pinon-images/videos/Spot_Taller_Pi_on_20_segundos_FULL_HD_FINAL_.ogg" type="video/ogg"/>
          <source src="https://s3-sa-east-1.amazonaws.com/pinon-images/videos/Spot_Taller_Pi_on_20_segundos_FULL_HD_FINAL_.webm" type="video/webm"/>
          Your browser does not support the video tag. I suggest you upgrade your browser.
        </video> 
      </div> <!--  end video-container -->
      <!-- LOGO sobre el video -->
      <!-- <div class="row">
        <div class="logo-over-video col-md-2 col-md-offset-3">
          <%= link_to image_tag("logo_video2.png", alt: "Taller Piñon logo", size:'640x480'), root_url %>
        </div>
      </div> -->

      <!-- Botones -->
      <div class="row">
        <div class="center col-md-8 col-md-offset-2" style="margin-top: 30%;">
        <div class="col-md-4 col-md-offset-2">
          <!--          <%= link_to "Customiza tu Vizcacha", customapp_path(:modelo => 'vizcacha'), method: :get, class:'btn btn-primary'%>-->
        </div> 
        <div class="col-md-4 ">
          <!--          <%= link_to "Customiza tu Jacana", customapp_path(:modelo => 'jacana'), method: :get , class:'btn btn-primary'%>-->
        </div>
          <!-- <%= link_to "Customiza tu moto!", customapp_path, method: 'get', class: "btn btn-lg btn-primary" %>-->
          <!-- <%= link_to "Únete a la comunidad Piñon!", signup_path, class: "btn btn-lg btn-primary" %> -->
        </div>
      </div>
      </div>
    </div> <!-- end .header-unit -->


  <% end %>

  <p id="que-hacemos" > </p>
  <br >
<div class="jumbo-img" style="background: url('<%=image_path('moto0.jpg') %>') no-repeat center center fixed; "> 
  <div class="espaco-imagem"> 
      <h1 class="titulo-default"> DISEÑO Y FABRICACIÓN DE MOTOS <br> <h2 style='color: #fff;font-size: 30px; margin-top: -20px'> Cafe racer | Scrambler</h2></h1>
    </br></br>
      <h2 style='color: #fff;font-size: 30px;'> <%= link_to 'Customiza', customapp_path  %> tu moto y nosotros la fabricamos  </h2>
      <div class="row">
        <div class="center col-md-8 col-md-offset-2" style="margin-top:0%;">
          <div class="col-md-4 col-md-offset-2">
            <%= link_to image_tag("custom_app/vizcacha_logo.png", size:'150x150'), customapp_path(:modelo => 'vizcacha'), method: :get %>
          </div> 
          <div class="col-md-4 ">
            <%= link_to image_tag("custom_app/jacana_logo.png", size:'150x150'), customapp_path(:modelo => 'jacana'), method: :get%>
          </div>
        </div>
      </div>
    </br>
  </div>
</div>
          <p class='center'style=' font-size: 20px;color: #fff; background-color: rgba(0,0,0,.7);'> Y te invitamos a participar de una comunidad de amantes del diseño y fabricación de motos. <%= link_to "Únete", signup_path %></p>

  <br >
  <p id="galeria-motos"> </p>
  <br >
    <div class="container"  >
 <!--       <div class="jumbotron"> -->
    <h1 class="titulo-mono"> MOTOS PIÑON</h1>
             <%= render 'static_pages/galeria_pinon' %>
          <p class='center'> <%= link_to 'ver más', index_pinon_path  %> </p>
 <!--       </div> -->
    </div>



<% end %>

app/views/static_pages/tu_pinon.html.erb
<!--
<h1> <%= @userPinon.motos.count %> Motos </h1>
<h2 class="center"> Cotiza tu piñon  </h2>
  -->

<!-- Metodo temporal antes de implementar un modelo MotoPiñon -->
<% @motosPinon.each do |m| %>
<% @moto = m %>
<% @modelo = m.modelo %>
<% @precio = m.precio %>
<ul class='motos-preview' >
    <%= render 'motopinon' %>
</ul>
<% end %>