config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  #root :to => redirect("https://www.facebook.com/tallerpinon?fref=ts")

	get	'home' => 'static_pages#home'
	get	'help' => 'static_pages#help'
	get 'about' => 'static_pages#about'
	get 'customapp' => 'static_pages#customapp'
	post 'fetch_pieza' => 'static_pages#fetch_pieza'
	post 'save_changes' => 'static_pages#save_changes'
	post 'contact_create' => 'static_pages#contact_create'
	get 'tu_pinon' => 'static_pages#tu_pinon'
	get 'contact' => 'static_pages#contact'
	get 'signup' => 'users#new'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  
	resources :users do
    member do
      get :following, :followers
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :motos,               only: [:index, :new, :create, :destroy, :edit, :update, :show]
  get 'index_pinon' => 'motos#indexPinon'
  
  resources :custom_apps,          only: [:create, :destroy, :update, :index, :show, :index]
  post 'recarga' => 'custom_apps#recarga'

  get 'auth/:provider/callback', to: 'users#omniauth_listener'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :logged_in_user, only: [:share, :save_changes]

  def home
    if logged_in?
      @micropost = current_user.microposts.build 
      @feed_items = current_user.feed.paginate(page: params[:page],:per_page => 10) # feed declared in user model.
    end
    @userPinon = User.find_by(email: 'contacto@tallerpinon.cl') #userPinon para mostrar las motos piñon
    if !@userPinon.nil?  # I had to put this in order to pass the test 
      @motos = @userPinon.motos.paginate(page: params[:page],  :per_page => 2) 
    end
  end

  def customapp 
    @modelo = params[:modelo]
    gon.archivos 
    gon.update_path
    if logged_in?
      if current_user.custom_apps.any?
        @customapp = current_user.custom_apps
        
        if customapp_in?
          crea_gon_object(current_custom.est_per_file, current_custom.apl_per_file, current_custom.asi_per_file, current_custom.man_per_file, current_custom.lla_per_file, current_custom.foc_per_file, "custom_app/#{current_custom.modelo}/perspectiva/per_plantilla.png", @modelo) # crea objeto gon, con los datos de color de las partes de la moto => gon.archivos
          gon.update_path = custom_app_path(@customapp)  
        end
#        puts @customapp.est_lat_file
      end
    end
  end

  def tu_pinon
    @userPinon = User.find_by(email: 'contacto@tallerpinon.cl') 
    @motosPinon = @userPinon.motos.paginate(page: params[:page],  :per_page => 2) 
  end

  def share
    # To implement for record the data inside CustomApp
  end 
 

  def save_changes

    if logged_in?
     redirect_to customapp_path
    end

  end

  def fetch_pieza
    color =  params[:color]
    parte = params[:parte]
    modelo = params[:modelo]
    color = color.upcase
    @per_file = "custom_app/"+modelo+"/perspectiva/per_"+parte+"_"+color+".png"
    @lat_file = "custom_app/"+modelo+"/lateral/lat_"+parte+"_"+color+".png"
    @sup_file = "custom_app/"+modelo+"/superior/sup_"+parte+"_"+color+".png"
    per_r = ActionController::Base.helpers.asset_path @per_file
    lat_r = ActionController::Base.helpers.asset_path @lat_file
    sup_r = ActionController::Base.helpers.asset_path @sup_file 
    render :json => { :per => per_r, :lat => lat_r , :sup => sup_r } 
  end

  def help
  end

	def about
	end

	def contact
    @nombre = params[:name]
    @email = params[:email]
    @custom_id = params[:custom_id]
    @modelo = params[:modelo]
	end

  def contact_create
    @contacto = params[:contact]

#    ContactMailer.contact_form(@contacto).deliver
    ContactMailer.delay.contact_form(@contacto)
    flash[:info] = "Tu mensaje ha sido enviado!"
    redirect_to root_url
  end

  private

    def crea_gon_object(est, apl, asi, man, lla, foc, base, modelo)
      color_est = get_color_from_path est
      color_apl = get_color_from_path apl
      color_asi = get_color_from_path asi
      color_man = get_color_from_path man
      color_lla = get_color_from_path lla
      color_foc = get_color_from_path foc
      
      #archivos del estanque
          @est_pf = ActionController::Base.helpers.asset_path "custom_app/"+modelo.to_s+"/perspectiva/per_estanque_"+color_est.to_s+".png" 
          @est_lf = ActionController::Base.helpers.asset_path "custom_app/"+modelo.to_s+"/lateral/lat_estanque_"+color_est.to_s+".png"
          @est_sf = ActionController::Base.helpers.asset_path "custom_app/"+modelo.to_s+"/superior/sup_estanque_"+color_est.to_s+".png"
      #archivos de la aplicacion del estanque
          @apl_pf = ActionController::Base.helpers.asset_path "custom_app/"+modelo.to_s+"/perspectiva/per_aplicacion_"+color_apl.to_s+".png"
          @apl_lf = ActionController::Base.helpers.asset_path "custom_app/"+modelo.to_s+"/lateral/lat_aplicacion_"+color_apl.to_s+".png"
          @apl_sf = ActionController::Base.helpers.asset_path "custom_app/"+modelo.to_s+"/superior/sup_aplicacion_"+color_apl.to_s+".png"
      #archivos del asiento 
          @asi_pf = ActionController::Base.helpers.asset_path "custom_app/"+modelo.to_s+"/perspectiva/per_asiento_"+color_asi.to_s+".png"
          @asi_lf = ActionController::Base.helpers.asset_path "custom_app/"+modelo.to_s+"/lateral/lat_asiento_"+color_asi.to_s+".png"
          @asi_sf = ActionController::Base.helpers.asset_path "custom_app/"+modelo.to_s+"/superior/sup_asiento_"+color_asi.to_s+".png"
      #manillar
          @man_pf = ActionController::Base.helpers.asset_path "custom_app/"+modelo.to_s+"/perspectiva/per_manilla_"+color_man.to_s+".png" 
          @man_lf = ActionController::Base.helpers.asset_path "custom_app/"+modelo.to_s+"/lateral/lat_manilla_"+color_man.to_s+".png"
          @man_sf = ActionController::Base.helpers.asset_path "custom_app/"+modelo.to_s+"/superior/sup_manilla_"+color_man.to_s+".png"
      # llantas
          @lla_pf = ActionController::Base.helpers.asset_path "custom_app/"+modelo.to_s+"/perspectiva/per_llanta_"+color_lla.to_s+".png" 
          @lla_lf = ActionController::Base.helpers.asset_path "custom_app/"+modelo.to_s+"/lateral/lat_llanta_"+color_lla.to_s+".png"
          @lla_sf = ActionController::Base.helpers.asset_path "custom_app/"+modelo.to_s+"/superior/sup_llanta_"+color_lla.to_s+".png"
      # Focos
          @foc_pf = ActionController::Base.helpers.asset_path "custom_app/"+modelo.to_s+"/perspectiva/per_foco_"+color_foc.to_s+".png" 
          @foc_lf = ActionController::Base.helpers.asset_path "custom_app/"+modelo.to_s+"/lateral/lat_foco_"+color_foc.to_s+".png"
          @foc_sf = ActionController::Base.helpers.asset_path "custom_app/"+modelo.to_s+"/superior/sup_foco_"+color_foc.to_s+".png"
          
          gon.archivos = { est_pf: @est_pf, est_lf: @est_lf, est_sf: @est_sf,
                           apl_pf: @apl_pf, apl_lf: @apl_lf, apl_sf: @apl_sf,
                           asi_pf: @asi_pf, asi_lf: @asi_lf, asi_sf: @asi_sf,
                           man_pf: @man_pf, man_lf: @man_lf, man_sf: @man_sf, 
                           lla_pf: @lla_pf, lla_lf: @lla_lf, lla_sf: @lla_sf, 
                           foc_pf: @foc_pf, foc_lf: @foc_lf, foc_sf: @foc_sf} 
   end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
    def get_color_from_path (p)
      color_est = /(_)([0-9A-F])+/.match(p)
      color_est = /([0-9A-F])+/.match(color_est.to_s)
    end 
end

app/views/static_pages/customapp_partials/_custombuttons.html.erb
<div class="container menu-custom"  style='background-color: #000; border-radius: 60px; height: 130px;'  >
  <div class="row ">
    <div class="col-xs-2 ">
      <ul class="nav navbar-nav navbar-left customButton">
          <li class="dropdown">
            <%= link_to image_tag('custom_app/est-icon.png', alt:'estanque icon', style:'max-width:100px; height:auto; '), '#', class:'dropdown-toogle btn-parte-moto', :data => {:toggle=>"dropdown"}%>
            <ul class="dropdown-menu">
              <li>
                <ul class='kwicks kwicks-horizontal'>
                  <% 23.times do |x| %>
                    <li id='panel-0<%=x%>'> </li> 
                  <% end %>
                </ul>
              </li>
            </ul>
          </li>

      </ul>
  </div>
    <div class="col-xs-2">
    <ul class="nav navbar-nav navbar-right customButton">
          <li class="dropdown">
            <%= link_to image_tag('custom_app/apl-icon.png', alt:'estanque icon', style:'max-width:100px; height:auto;'), '#', class:'dropdown-toogle  btn-parte-moto', :data => {:toggle=>"dropdown"}%>
            <ul class="dropdown-menu">
              <li>
                <ul class='kwicks kwicks-horizontal'>
                  <% 23.times do |x| %>
                    <li id='panel-1<%=x%>'> </li> 
                  <% end %>
                </ul>
              </li>
            </ul>
          </li>
    </ul>
  </div>
    <div class="col-xs-2">
    <ul class="nav navbar-nav navbar-right customButton">
          <li class="dropdown">
            <%= link_to image_tag('custom_app/asi-icon.png', alt:'estanque icon', style:'max-width:100px; height:auto;'), '#', class:'dropdown-toogle btn-parte-moto', :data => {:toggle=>"dropdown"}%>
            <ul class="dropdown-menu">
              <li>
                <ul class='kwicks kwicks-horizontal'>
                  <% 10.times do |x| %>
                    <li id='panel-2<%=x%>'> </li> 
                  <% end %>
                </ul>
              </li>
            </ul>
          </li>
    </ul>
  </div>
    <div class="col-xs-2">
    <ul class="nav navbar-nav navbar-right customButton">
          <li class="dropdown">
            <%= link_to image_tag('custom_app/man-icon.png', alt:'estanque icon', style:'max-width:100px; height:auto;'), '#', class:'dropdown-toogle btn-parte-moto', :data => {:toggle=>"dropdown"}%>
            <ul class="dropdown-menu">
              <li>
                <ul class='kwicks kwicks-horizontal'>
                  <% 10.times do |x| %>
                    <li id='panel-3<%=x%>'> </li> 
                  <% end %>
                </ul>
              </li>
            </ul>
          </li>
    </ul>
  </div>
    <div class="col-xs-2">
    <ul class="nav navbar-nav navbar-right customButton">
          <li class="dropdown">
            <%= link_to image_tag('custom_app/lla-icon.png', alt:'estanque icon', style:'max-width:100px; height:auto;'), '#', class:'dropdown-toogle btn-parte-moto', :data => {:toggle=>"dropdown"}%>
            <ul class="dropdown-menu">
              <li>
                <ul class='kwicks kwicks-horizontal'>
                  <% 23.times do |x| %>
                    <li id='panel-4<%=x%>'> </li> 
                  <% end %>
                </ul>
              </li>
            </ul>
          </li>
    </ul>
  </div>
    <div class="col-xs-2">
    <ul class="nav navbar-nav navbar-right customButton">
          <li class="dropdown">
            <%= link_to image_tag('custom_app/foc-icon.png', alt:'estanque icon', style:'max-width:100px; height:auto;'), '#', class:'dropdown-toogle btn-parte-moto', :data => {:toggle=>"dropdown"}%>
            <ul class="dropdown-menu">
              <li>
                <ul class='kwicks kwicks-horizontal'>
                  <% 23.times do |x| %>
                    <li id='panel-5<%=x%>'> </li> 
                  <% end %>
                </ul>
              </li>
            </ul>
          </li>
    </ul>
  </div>
  </div>
</div>

app/views/static_pages/customapp_partials/_customdisplays_jacana.html.erb
<!-- DISPLAYS -->
<div class="row">
  <div class="col-md-8  ">
    <div class="plantilla-moto">
    <%= image_tag("custom_app/area_transparente.png", alt: "per-est-app", style:'max-width:100%; height:auto;', id:'per-est-app', class:'capa-moto' )%>
    <%= image_tag("custom_app/area_transparente.png", alt: "per-apl-app", style:'max-width:100%; height:auto;', id:'per-apl-app', class:'capa-moto' )%>
    <%= image_tag("custom_app/area_transparente.png", alt: "per-asi-app", style:'max-width:100%; height:auto;', id:'per-asi-app', class:'capa-moto' )%>
    <%= image_tag("custom_app/area_transparente.png", alt: "per-man-app", style:'max-width:100%; height:auto;', id:'per-man-app', class:'capa-moto' )%>
    <%= image_tag("custom_app/area_transparente.png", alt: "per-lla-app", style:'max-width:100%; height:auto;', id:'per-lla-app', class:'capa-moto' )%>
    <%= image_tag("custom_app/area_transparente.png", alt: "per-foc-app", style:'max-width:100%; height:auto;', id:'per-foc-app', class:'capa-moto' )%>
    <%= image_tag("custom_app/jacana/perspectiva/per_plantilla.png", alt: "per-pla-app", style:'max-width:100%; height:auto;', id:'per-pla-app', class:'capa-moto' )%>
    <%= image_tag("custom_app/area_transparente.png", alt: "test moto img", style:'max-width:100%; height:auto;', class:'capa-moto-ultima')%>
    </div>
  </div>
  <div class="col-md-4 ">
    <div class="row ">
      <div class="col-md-12">
        <div class="plantilla-moto">
    <%= image_tag("custom_app/area_transparente.png", alt: "sup-est-app", style:'max-width:100%; height:auto;', id:'sup-est-app', class:'capa-moto' )%>
    <%= image_tag("custom_app/area_transparente.png", alt: "sup-apl-app", style:'max-width:100%; height:auto;', id:'sup-apl-app', class:'capa-moto' )%>
    <%= image_tag("custom_app/area_transparente.png", alt: "sup-asi-app", style:'max-width:100%; height:auto;', id:'sup-asi-app', class:'capa-moto' )%>
    <%= image_tag("custom_app/area_transparente.png", alt: "sup-man-app", style:'max-width:100%; height:auto;', id:'sup-man-app', class:'capa-moto' )%>
    <%= image_tag("custom_app/area_transparente.png", alt: "sup-lla-app", style:'max-width:100%; height:auto;', id:'sup-lla-app', class:'capa-moto' )%>
    <%= image_tag("custom_app/area_transparente.png", alt: "sup-foc-app", style:'max-width:100%; height:auto;', id:'sup-foc-app', class:'capa-moto' )%>
    <%= image_tag("custom_app/jacana/superior/sup_plantilla.png", alt: "sup-pla-app", style:'max-width:100%; height:auto;', id:'sup-pla-app', class:'capa-moto' )%>
    <%= image_tag("custom_app/area_transparente.png", alt: "area transparente", style:'max-width:100%; height:auto;')%>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="plantilla-moto">
    <%= image_tag("custom_app/area_transparente.png", alt: "lat-est-app", style:'max-width:100%; height:auto;', id:'lat-est-app', class:'capa-moto' )%>
    <%= image_tag("custom_app/area_transparente.png", alt: "lat-apl-app", style:'max-width:100%; height:auto;', id:'lat-apl-app', class:'capa-moto' )%>
    <%= image_tag("custom_app/area_transparente.png", alt: "lat-asi-app", style:'max-width:100%; height:auto;', id:'lat-asi-app', class:'capa-moto' )%>
    <%= image_tag("custom_app/area_transparente.png", alt: "lat-man-app", style:'max-width:100%; height:auto;', id:'lat-man-app', class:'capa-moto' )%>
    <%= image_tag("custom_app/area_transparente.png", alt: "lat-lla-app", style:'max-width:100%; height:auto;', id:'lat-lla-app', class:'capa-moto' )%>
    <%= image_tag("custom_app/area_transparente.png", alt: "lat-foc-app", style:'max-width:100%; height:auto;', id:'lat-foc-app', class:'capa-moto' )%>
    <%= image_tag("custom_app/jacana/lateral/lat_plantilla.png", alt: "test moto img", style:'max-width:100%; height:auto;', id:'lat-pla-app', class:'capa-moto' )%>
    <%= image_tag("custom_app/area_transparente.png", alt: "test moto img", style:'max-width:100%; height:auto;')%>
        </div>
      </div>
    </div>
  </div>

</div>

  <p style='color:#101010;' class='center'> Presiona F11 para ver la aplicación en pantalla completa </p>

app/views/static_pages/customapp_partials/_customdisplays_vizcacha.html.erb
<!-- DISPLAYS -->
<div class="row">
  <div class="col-md-8  ">
    <div class="plantilla-moto">
    <%= image_tag("custom_app/area_transparente.png", alt: "per-est-app", style:'max-width:100%; height:auto;', id:'per-est-app', class:'capa-moto' )%>
    <%= image_tag("custom_app/area_transparente.png", alt: "per-apl-app", style:'max-width:100%; height:auto;', id:'per-apl-app', class:'capa-moto' )%>
    <%= image_tag("custom_app/area_transparente.png", alt: "per-asi-app", style:'max-width:100%; height:auto;', id:'per-asi-app', class:'capa-moto' )%>
    <%= image_tag("custom_app/area_transparente.png", alt: "per-man-app", style:'max-width:100%; height:auto;', id:'per-man-app', class:'capa-moto' )%>
    <%= image_tag("custom_app/area_transparente.png", alt: "per-lla-app", style:'max-width:100%; height:auto;', id:'per-lla-app', class:'capa-moto' )%>
    <%= image_tag("custom_app/area_transparente.png", alt: "per-foc-app", style:'max-width:100%; height:auto;', id:'per-foc-app', class:'capa-moto' )%>
    <%= image_tag("custom_app/vizcacha/perspectiva/per_plantilla.png", alt: "per-pla-app", style:'max-width:100%; height:auto;', id:'per-pla-app', class:'capa-moto' )%>
    <%= image_tag("custom_app/area_transparente.png", alt: "test moto img", style:'max-width:100%; height:auto;', class:'capa-moto-ultima')%>
    </div>
  </div>
  <div class="col-md-4 ">
    <div class="row ">
      <div class="col-md-12">
        <div class="plantilla-moto">
    <%= image_tag("custom_app/area_transparente.png", alt: "sup-est-app", style:'max-width:100%; height:auto;', id:'sup-est-app', class:'capa-moto' )%>
    <%= image_tag("custom_app/area_transparente.png", alt: "sup-apl-app", style:'max-width:100%; height:auto;', id:'sup-apl-app', class:'capa-moto' )%>
    <%= image_tag("custom_app/area_transparente.png", alt: "sup-asi-app", style:'max-width:100%; height:auto;', id:'sup-asi-app', class:'capa-moto' )%>
    <%= image_tag("custom_app/area_transparente.png", alt: "sup-man-app", style:'max-width:100%; height:auto;', id:'sup-man-app', class:'capa-moto' )%>
    <%= image_tag("custom_app/area_transparente.png", alt: "sup-lla-app", style:'max-width:100%; height:auto;', id:'sup-lla-app', class:'capa-moto' )%>
    <%= image_tag("custom_app/area_transparente.png", alt: "sup-foc-app", style:'max-width:100%; height:auto;', id:'sup-foc-app', class:'capa-moto' )%>
    <%= image_tag("custom_app/vizcacha/superior/sup_plantilla.png", alt: "sup-pla-app", style:'max-width:100%; height:auto;', id:'sup-pla-app', class:'capa-moto' )%>
    <%= image_tag("custom_app/area_transparente.png", alt: "area transparente", style:'max-width:100%; height:auto;')%>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="plantilla-moto">
    <%= image_tag("custom_app/area_transparente.png", alt: "lat-est-app", style:'max-width:100%; height:auto;', id:'lat-est-app', class:'capa-moto' )%>
    <%= image_tag("custom_app/area_transparente.png", alt: "lat-apl-app", style:'max-width:100%; height:auto;', id:'lat-apl-app', class:'capa-moto' )%>
    <%= image_tag("custom_app/area_transparente.png", alt: "lat-asi-app", style:'max-width:100%; height:auto;', id:'lat-asi-app', class:'capa-moto' )%>
    <%= image_tag("custom_app/area_transparente.png", alt: "lat-man-app", style:'max-width:100%; height:auto;', id:'lat-man-app', class:'capa-moto' )%>
    <%= image_tag("custom_app/area_transparente.png", alt: "lat-lla-app", style:'max-width:100%; height:auto;', id:'lat-lla-app', class:'capa-moto' )%>
    <%= image_tag("custom_app/area_transparente.png", alt: "lat-foc-app", style:'max-width:100%; height:auto;', id:'lat-foc-app', class:'capa-moto' )%>
    <%= image_tag("custom_app/vizcacha/lateral/lat_plantilla.png", alt: "test moto img", style:'max-width:100%; height:auto;', id:'lat-pla-app', class:'capa-moto' )%>
    <%= image_tag("custom_app/area_transparente.png", alt: "test moto img", style:'max-width:100%; height:auto;')%>
        </div>
      </div>
    </div>
  </div>

</div>

  <p style='color:#101010;' class='center'> Presiona F11 para ver la aplicación en pantalla completa </p>

app/views/static_pages/customapp_partials/_customlinks.html.erb
<div class="row">
<% if logged_in? %>
    <div class="col-md-4 col-md-offset-2">
      <%= link_to "comparte en redes sociales!", '', id:'guardar-nueva-customapp', class:'btn btn-info'%>
    </div>
    <div class="col-md-4 ">
      <%= link_to "cotizar!", '', id:'guardar-nueva-customapp-cotiza', class:'btn btn-success'%>
    </div>
<% else %>
  <% store_location %>
    <div class="col-md-6 col-md-offset-3">
    <%= link_to "registrate para compartir o cotizar tu moto", save_changes_path, method: 'post', class:'btn btn-primary'%>
  </div>
  <% end %>
</div>


<!--    <div class="col-md-3 col-md-offset-3">
      <%= link_to "guardar cambios", '', id:'actualiza-customapp', class:'btn btn-primary'%>
    </div> -->

app/views/static_pages/customapp_partials/_miscustoms.html.erb
<h1> Mis customizaciones </h1>

<% if !@customapp.nil? %>
  <div class="row">
  <% @customapp.each do |capp| %>
    <div class="col-md-2">
      <div class="plantilla-moto">
      <%= image_tag( capp.est_per_file, alt: "per-est-app", style:'max-width:100%; height:auto;', id:'per-est-app-'+capp.id.to_s, class:'capa-moto' )%>
      <%= image_tag(capp.apl_per_file, alt: "per-apl-app", style:'max-width:100%; height:auto;', id:'per-apl-app-'+capp.id.to_s, class:'capa-moto' )%>
      <%= image_tag(capp.asi_per_file, alt: "per-asi-app", style:'max-width:100%; height:auto;', id:'per-asi-app-'+capp.id.to_s, class:'capa-moto' )%> 
      <%= image_tag(capp.man_per_file, alt: "per-man-app", style:'max-width:100%; height:auto;', id:'per-man-app-'+capp.id.to_s, class:'capa-moto' )%>
      <%= image_tag(capp.lla_per_file, alt: "per-lla-app", style:'max-width:100%; height:auto;', id:'per-lla-app-'+capp.id.to_s, class:'capa-moto' )%>
      <%= image_tag(capp.foc_per_file, alt: "per-foc-app", style:'max-width:100%; height:auto;', id:'per-foc-app-'+capp.id.to_s, class:'capa-moto' )%>
      <%= image_tag("custom_app/#{capp.modelo}/perspectiva/per_plantilla.png", alt: "per-pla-app", style:'max-width:100%; height:auto;', id:'per-pla-app-'+capp.id.to_s, class:'capa-moto' )%>
      <%= image_tag("custom_app/area_transparente.png", alt: "test moto img", style:'max-width:100%; height:auto;', class:'capa-moto-ultima')%>
    </div>
    <% if current_user?(capp.user) %>
      <p class="center">
      <%= link_to "ver", custom_app_path(:id => capp.id), method: :get, id: 'ver-motocustom' %> | 
      <%= link_to "editar", recarga_path(:id => capp.id), method: :post %> | 
      <%= link_to "eliminar", custom_app_path(:id => capp.id), method: :delete, data: {confirm: "Estas seguro de eliminar esta customizacion?"}%>
    </p>
    <div class="col-md-12">
      <% usuario = User.find_by(id: capp.user_id) %>
      <%= link_to "cotizar modelo", contact_path(:name => usuario.name, :email => usuario.email, :custom_id => capp.id, :modelo => capp.modelo  )  ,  class:'btn btn-success'%>
    </div>
    <% end %>
  </div>
  <% end %>
 </div> 
<% end %>