config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  #root :to => redirect("https://www.facebook.com/tallerpinon?fref=ts")

	get	'home' => 'static_pages#home'
	get	'help' => 'static_pages#help'
	get 'about' => 'static_pages#about'
	get 'customapp' => 'static_pages#customapp'
	post 'fetch_pieza' => 'static_pages#fetch_pieza'
	post 'save_changes' => 'static_pages#save_changes'
	post 'contact_create' => 'static_pages#contact_create'
	get 'tu_pinon' => 'static_pages#tu_pinon'
	get 'contact' => 'static_pages#contact'
	get 'signup' => 'users#new'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  
	resources :users do
    member do
      get :following, :followers
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :motos,               only: [:index, :new, :create, :destroy, :edit, :update, :show]
  get 'index_pinon' => 'motos#indexPinon'
  
  resources :custom_apps,          only: [:create, :destroy, :update, :index, :show, :index]
  post 'recarga' => 'custom_apps#recarga'

  get 'auth/:provider/callback', to: 'users#omniauth_listener'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <% err = pluralize(object.errors.count, "error" )%>
      El formulario contiene <%= object.errors.count%> <%= err=="error"? "error" : "errores"  %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <div class="col-md-offset-2">
    <%= will_paginate @feed_items %>
  </div>
<% end %>

app/views/shared/_galeria_jacana.html.erb
<!-- The Gallery as lightbox dialog, should be a child element of the document body -->
<div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls">
    <div class="slides"></div>
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
</div>

<div id="links">
    <a href="https://s3-sa-east-1.amazonaws.com/pinon-images/static_images/jacana_galeria/01b.jpg" title="">
        <img src="https://s3-sa-east-1.amazonaws.com/pinon-images/static_images/jacana_galeria/01b_thumb.jpg" class="thumb-galery"  alt="">
    </a>
    <a href="https://s3-sa-east-1.amazonaws.com/pinon-images/static_images/jacana_galeria/jacana_galeria/02b.jpg" title="">
        <img src="https://s3-sa-east-1.amazonaws.com/pinon-images/static_images/jacana_galeria/02b_thumb.jpg" class="thumb-galery" alt="">
    </a>
    <a href="https://s3-sa-east-1.amazonaws.com/pinon-images/static_images/jacana_galeria/03.jpg" title="">
        <img src="https://s3-sa-east-1.amazonaws.com/pinon-images/static_images/jacana_galeria/03_thumb.jpg" class="thumb-galery" alt="">
    </a>
    <a href="https://s3-sa-east-1.amazonaws.com/pinon-images/static_images/jacana_galeria/04.jpg" title="">
        <img src="https://s3-sa-east-1.amazonaws.com/pinon-images/static_images/jacana_galeria/04_thumb.jpg" class="thumb-galery" alt="">
    </a>
    <a href="https://s3-sa-east-1.amazonaws.com/pinon-images/static_images/jacana_galeria/05.jpg" title="">
        <img src="https://s3-sa-east-1.amazonaws.com/pinon-images/static_images/jacana_galeria/05_thumb.jpg" class="thumb-galery" alt="">
    </a>
    <a href="https://s3-sa-east-1.amazonaws.com/pinon-images/static_images/jacana_galeria/06.jpg" title="">
        <img src="https://s3-sa-east-1.amazonaws.com/pinon-images/static_images/jacana_galeria/06_thumb.jpg" class="thumb-galery" alt="">
    </a>
    <a href="https://s3-sa-east-1.amazonaws.com/pinon-images/static_images/jacana_galeria/07.jpg" title="">
        <img src="https://s3-sa-east-1.amazonaws.com/pinon-images/static_images/jacana_galeria/07_thumb.jpg" class="thumb-galery" alt="">
    </a>
    <a href="https://s3-sa-east-1.amazonaws.com/pinon-images/static_images/jacana_galeria/08.jpg" title="">
        <img src="https://s3-sa-east-1.amazonaws.com/pinon-images/static_images/jacana_galeria/08_thumb.jpg" class="thumb-galery" alt="">
    </a>
    <a href="https://s3-sa-east-1.amazonaws.com/pinon-images/static_images/jacana_galeria/09.jpg" title="">
        <img src="https://s3-sa-east-1.amazonaws.com/pinon-images/static_images/jacana_galeria/09_thumb.jpg" class="thumb-galery" alt="">
    </a>
    <a href="https://s3-sa-east-1.amazonaws.com/pinon-images/static_images/jacana_galeria/10a.jpg" title="">
        <img src="https://s3-sa-east-1.amazonaws.com/pinon-images/static_images/jacana_galeria/10a_thumb.jpg" class="thumb-galery" alt="">
    </a>
    <a href="https://s3-sa-east-1.amazonaws.com/pinon-images/static_images/jacana_galeria/10b.jpg" title="">
        <img src="https://s3-sa-east-1.amazonaws.com/pinon-images/static_images/jacana_galeria/10b_thumb.jpg" class="thumb-galery" alt="">
    </a>
    <a href="https://s3-sa-east-1.amazonaws.com/pinon-images/static_images/jacana_galeria/12.jpg" title="">
        <img src="https://s3-sa-east-1.amazonaws.com/pinon-images/static_images/jacana_galeria/12_thumb.jpg" class="thumb-galery" alt="">
    </a>
</div>
<script>
document.getElementById('links').onclick = function (event) {
    event = event || window.event;
    var target = event.target || event.srcElement,
        link = target.src ? target.parentNode : target,
        options = {index: link, event: event},
        links = this.getElementsByTagName('a');
    blueimp.Gallery(links, options);
};
</script>


<script src="//blueimp.github.io/Gallery/js/jquery.blueimp-gallery.min.js"></script>
<script src="js/bootstrap-image-gallery.min.js"></script>

app/views/shared/_galeria_vizcacha.html.erb
<!-- The Gallery as lightbox dialog, should be a child element of the document body -->
<div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls">
    <div class="slides"></div>
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
</div>

<div id="links">
    <a href="https://s3-sa-east-1.amazonaws.com/pinon-images/static_images/vizcacha_galeria/Vizcacha_01.jpg" title="">
        <img src="https://s3-sa-east-1.amazonaws.com/pinon-images/static_images/vizcacha_galeria/Vizcacha_01_thumb.jpg" class="thumb-galery"  alt="">
    </a>
    <a href="https://s3-sa-east-1.amazonaws.com/pinon-images/static_images/vizcacha_galeria/Vizcacha_02.jpg" title="">
    <img src="https://s3-sa-east-1.amazonaws.com/pinon-images/static_images/vizcacha_galeria/Vizcacha_02_thumb.jpg" class="thumb-galery"  alt="">
    </a>
    <a href="https://s3-sa-east-1.amazonaws.com/pinon-images/static_images/vizcacha_galeria/Vizcacha_03.jpg" title="">
    <img src="https://s3-sa-east-1.amazonaws.com/pinon-images/static_images/vizcacha_galeria/Vizcacha_03_thumb.jpg" class="thumb-galery"  alt="">
    </a>
    <a href="https://s3-sa-east-1.amazonaws.com/pinon-images/static_images/vizcacha_galeria/Vizcacha_04.jpg" title="">
    <img src="https://s3-sa-east-1.amazonaws.com/pinon-images/static_images/vizcacha_galeria/Vizcacha_04_thumb.jpg" class="thumb-galery"  alt="">
    </a>
    <a href="https://s3-sa-east-1.amazonaws.com/pinon-images/static_images/vizcacha_galeria/Vizcacha_05.jpg" title="">
    <img src="https://s3-sa-east-1.amazonaws.com/pinon-images/static_images/vizcacha_galeria/Vizcacha_05_thumb.jpg" class="thumb-galery"  alt="">
    </a>
    <a href="https://s3-sa-east-1.amazonaws.com/pinon-images/static_images/vizcacha_galeria/Vizcacha_06.jpg" title="">
    <img src="https://s3-sa-east-1.amazonaws.com/pinon-images/static_images/vizcacha_galeria/Vizcacha_06_thumb.jpg" class="thumb-galery"  alt="">
    </a>
    <a href="https://s3-sa-east-1.amazonaws.com/pinon-images/static_images/vizcacha_galeria/Vizcacha_07.jpg" title="">
    <img src="https://s3-sa-east-1.amazonaws.com/pinon-images/static_images/vizcacha_galeria/Vizcacha_07_thumb.jpg" class="thumb-galery"  alt="">
    </a>
    <a href="https://s3-sa-east-1.amazonaws.com/pinon-images/static_images/vizcacha_galeria/Vizcacha_08.jpg" title="">
    <img src="https://s3-sa-east-1.amazonaws.com/pinon-images/static_images/vizcacha_galeria/Vizcacha_08_thumb.jpg" class="thumb-galery"  alt="">
    </a>
    <a href="https://s3-sa-east-1.amazonaws.com/pinon-images/static_images/vizcacha_galeria/Vizcacha_09.jpg" title="">
    <img src="https://s3-sa-east-1.amazonaws.com/pinon-images/static_images/vizcacha_galeria/Vizcacha_09_thumb.jpg" class="thumb-galery"  alt="">
    </a>
    <a href="https://s3-sa-east-1.amazonaws.com/pinon-images/static_images/vizcacha_galeria/Vizcacha_10.jpg" title="">
    <img src="https://s3-sa-east-1.amazonaws.com/pinon-images/static_images/vizcacha_galeria/Vizcacha_10_thumb.jpg" class="thumb-galery"  alt="">
    </a>
    <a href="https://s3-sa-east-1.amazonaws.com/pinon-images/static_images/vizcacha_galeria/Vizcacha_11.jpg" title="">
    <img src="https://s3-sa-east-1.amazonaws.com/pinon-images/static_images/vizcacha_galeria/Vizcacha_11_thumb.jpg" class="thumb-galery"  alt="">
    </a>
    <a href="https://s3-sa-east-1.amazonaws.com/pinon-images/static_images/vizcacha_galeria/Vizcacha_12.jpg" title="">
    <img src="https://s3-sa-east-1.amazonaws.com/pinon-images/static_images/vizcacha_galeria/Vizcacha_12_thumb.jpg" class="thumb-galery"  alt="">
    </a>
    <a href="https://s3-sa-east-1.amazonaws.com/pinon-images/static_images/vizcacha_galeria/Vizcacha_13.jpg" title="">
    <img src="https://s3-sa-east-1.amazonaws.com/pinon-images/static_images/vizcacha_galeria/Vizcacha_13_thumb.jpg" class="thumb-galery"  alt="">
    </a>
    <a href="https://s3-sa-east-1.amazonaws.com/pinon-images/static_images/vizcacha_galeria/Vizcacha_14.jpg" title="">
    <img src="https://s3-sa-east-1.amazonaws.com/pinon-images/static_images/vizcacha_galeria/Vizcacha_14_thumb.jpg" class="thumb-galery"  alt="">
    </a>
    <a href="https://s3-sa-east-1.amazonaws.com/pinon-images/static_images/vizcacha_galeria/Vizcacha_15.jpg" title="">
    <img src="https://s3-sa-east-1.amazonaws.com/pinon-images/static_images/vizcacha_galeria/Vizcacha_15_thumb.jpg" class="thumb-galery"  alt="">
    </a>
</div>
<script>
document.getElementById('links').onclick = function (event) {
    event = event || window.event;
    var target = event.target || event.srcElement,
        link = target.src ? target.parentNode : target,
        options = {index: link, event: event},
        links = this.getElementsByTagName('a');
    blueimp.Gallery(links, options);
};
</script>


<script src="//blueimp.github.io/Gallery/js/jquery.blueimp-gallery.min.js"></script>
<script src="js/bootstrap-image-gallery.min.js"></script>

app/views/shared/_loginview.html.erb
    <div class="row">
      <div class="col-md-4">
      <aside>
        <section class="user_info">
          <%= render 'shared/user_info' %>
        </section>
        <section class="stats">
          <%= render 'shared/stats' %>
        </section>
        <section class="micropost_form" %>
          <%= render 'shared/micropost_form' %>
        </section>
        <hr >
        <%= render 'shared/moto_form' %>
      </aside>
      </div>
      <div class="col-md-8">
        <h3> Comentarios </h3>
        <%= render 'shared/feed' %>
      </div>
    </div>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost, html: { multipart: true }) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Nuevo comentario..." %>
  </div>
  <%= f.submit "Enviar", class: "btn btn-primary" %>
  <span class="picture">
    <%= f.file_field :picture, accept: 'image/jpeg,image/jpg,image/gif,image/png' %>
  </span>
<% end %>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('El tamaño máximo para la imagen es 5MB. Por favor escoge un archivo mas pequeño.');
    }
  });
</script>

app/views/shared/_moto_form.html.erb
<!-- html para la conza de 'mis motos' en el home de la página p -->
<h3 class="center"> Mis motos </h3>

<ul class="motos-preview">
  <% @user.motos.paginate(page: params[:page], :per_page => 3).each do |moto| %>
    <li id="moto-<%= moto.id %>" >
      <div class="row">
        <div class="col-md-6">
          <% if moto.picture? %>
            <%= link_to image_tag(moto.picture.url, alt: "foto-moto", class:'moto-responsive'), moto_path(moto)  %>
          <% end %>
        </div>
        <div class="col-md-6">
          <span class="nombre"> <%= moto.name %></span> <br>
          <span class="modelo"> <%= moto.modelo %> </span> <br>
          <span>  <%= link_to 'ver detalles', moto_path(moto)  %> </span > <br>
          <span class="links">
            <% if current_user?(moto.user) %>
              <%= link_to "editar moto", edit_moto_path(moto)  %> <br>
              <%= link_to "eliminar moto", moto, method: :delete, data: { confirm: "Estas seguro?" } %>
            <% end %>
          </span> <br>
        </div>
      </div>
    </li>
  <% end %>
</ul>
<p class="center"><%= link_to 'nueva moto', new_moto_path %></p>
<div class="col-md-offset-2" style="margin-top: -30px">
<%= will_paginate @user.motos.paginate(page: params[:page], :per_page => 3) %>
</div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    siguiendo
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    seguidores
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size:50), current_user %>
<h3> <%= current_user.name %> </h3>
<span> <%= link_to "ver mi perfil publico", current_user %> </span>
<span> <%= pluralize(current_user.microposts.count, "comentarios") %> </span>