config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  #root :to => redirect("https://www.facebook.com/tallerpinon?fref=ts")

	get	'home' => 'static_pages#home'
	get	'help' => 'static_pages#help'
	get 'about' => 'static_pages#about'
	get 'customapp' => 'static_pages#customapp'
	post 'fetch_pieza' => 'static_pages#fetch_pieza'
	post 'save_changes' => 'static_pages#save_changes'
	post 'contact_create' => 'static_pages#contact_create'
	get 'tu_pinon' => 'static_pages#tu_pinon'
	get 'contact' => 'static_pages#contact'
	get 'signup' => 'users#new'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  
	resources :users do
    member do
      get :following, :followers
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :motos,               only: [:index, :new, :create, :destroy, :edit, :update, :show]
  get 'index_pinon' => 'motos#indexPinon'
  
  resources :custom_apps,          only: [:create, :destroy, :update, :index, :show, :index]
  post 'recarga' => 'custom_apps#recarga'

  get 'auth/:provider/callback', to: 'users#omniauth_listener'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Taller Piñon 2015
    by <a href="http://www.javiercruz.cl/">Javier Cruz</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contacto", contact_path  %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_google_analytics.html.erb
<% if Rails.env.production? %>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-53836575-3', 'auto');
  ga('send', 'pageview');
</script>
<% end %>

app/views/layouts/_header.html.erb
<header itemscope itemtype="http://schema.org/LocalBusiness" class="navbar navbar-fixed-top ">
  <div class="container">
    <% if content_for?(:show_custom) %>
      <% if !logged_in? %>
         <!-- leave with no logo, to not appear in facebook share -->
      <% else %>
        <% logo = image_tag("logo_pagina2.png", :alt => "Taller Piñon", :class=> "logo", size:'64x48', :itemprop=>"image") %>
   <!--    <%= link_to logo, root_path , id: "logo" %> -->
      <% end %>
    <% else %>
        <% logo = image_tag("logo_pagina2.png", :alt => "Taller Piñon", :class=> "logo", size:'64x48', :itemprop=>"image") %>
        <%= link_to logo , root_path , id: "logo" %> 
    <% end %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",  root_path , class:"page-scroll", method: :get%></li>
        
        <% if !current_page?(contact_path) && !current_page?(about_path) && !current_page?(customapp_path) && !current_page?(login_path)%>
          <% if current_page?(root_path) %>
            <li><%= link_to "Que hacemos",  '#que-hacemos' , class:"page-scroll"%></li>
            <li><%= link_to "Motos Piñon",  '#galeria-motos' , class:"page-scroll"%></li>
          <% else %>
            <li><%= link_to "Que hacemos", root_path+'#que-hacemos' , class:"page-scroll"%></li>
            <li><%= link_to "Motos Piñon", root_path+'#galeria-motos' , class:"page-scroll"%></li>
          <% end %>
        <% end %>
        <li><%= link_to "Quienes somos",  about_path %></li>
        <li><%= link_to "Compra la tuya",  tu_pinon_path, style:'color: #0022ff'  %></li>

        <!-- Moto Custom Menu -->
        <li style="line-height: 47px;"> | </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toogle" data-toggle="dropdown">
              Moto Custom<b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Vizcacha", customapp_path(:modelo => 'vizcacha'), method: :get %> </li>
              <li><%= link_to "Jacana", customapp_path(:modelo => 'jacana'), method: :get %></li>
              <li class="divider"></li>
              <li> <%= link_to "Ver todas", custom_apps_path, method: "get" %> </li>
            </ul>
          </li>
          <!--     <li><%= link_to "Moto Custom", customapp_path, class:"page-scroll", method: :get %></li>-->
        <li style="line-height: 47px;"> | </li>

        <!-- Registro y logs in-out -->
        <% if logged_in? %>
<li class="dropdown">
            <a href="#" class="dropdown-toogle" data-toggle="dropdown">
              Usuarios <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Usuarios", users_path %> </li>
              <li class="divider"></li>
              <li><%= link_to "Motos", motos_path %></li>
            </ul>
          </li>

          <li style="line-height: 47px;"> | </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toogle" data-toggle="dropdown">
              Tu cuenta<b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Perfil", current_user %> </li>
              <li><%= link_to "Configuraciones", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li> <%= link_to "Salir", logout_path, method: "delete" %> </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Entrar", login_path %></li>
          <li><%= link_to "Registrate!", signup_path  %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <meta content="Taller Piñon" property="og:title"> 
    <meta content="Taller Piñon" property="og:site_name">
    <meta content="Porque amamos las motos vintage queremos revivirlas." property="og:description">
    <meta content="Taller Piñon" itemprop="name"> 
    <meta content="Porque amamos las motos vintage queremos revivirlas." itemprop="description">
    <meta content="Taller Piñon" name="twitter:title">
    <meta content="Porque amamos las motos vintage queremos revivirlas." name="twitter:description">
    <meta content="Porque amamos las motos vintage queremos revivirlas." name="description">
    <meta content="Moto, motocicleta, bike, motorcycle, Moto cafe racer, cafe racer Chile, Cafe racer Santiago, Cafe racer, modificación de motos, Triumph truxton, Scrambler, Scrambler Chile, Scrambler Santiago, Cafe, racer, caferacer" name="keywords">

    <meta name="description" content="Diseño y fabricación de motos. Cafe racer - Scrambler" />
    <meta name="google-site-verification" content="TNtuNYpMbZ1y6wzy64u4S0R2lLAWw2TGJRjtW5FIpds" />

    <title><%= full_title(yield(:title)) %></title>

     <meta property="og:type" content="website" />
     <meta property="og:image:type" content="image/jpeg" />
     <meta property="og:description"  content="Tú la customizas y nosotros la fabricamos" />
     <meta property="og:image:width" content="1200" />
     <meta property="og:image:height" content="630" />

    <%= include_gon %>
    

    <%= stylesheet_link_tag 'application', media: 'all','data-turbolinks-track' => true %>
    <link rel="stylesheet" href="css/blueimp-gallery.min.css">
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>

    <%= render 'layouts/google_analytics' %>
  </head>
  <body style="background-color: black;">

    <%= render 'layouts/header' %>

    <!-- MESSAGES -->
    <div class="container" id="flash">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    </div>


  

    <!-- CONTENT -->
    <% if content_for?(:home) %>
      <%= yield(:home) %>
    <% elsif content_for?(:show_moto) %>
      <%= yield(:show_moto) %>
    <% elsif content_for?(:custom) %>
      <%= yield(:custom) %>
    <% elsif content_for?(:show_custom) %>
       <div class="container">
        <%= yield(:show_custom) %>
       </div>
    <% else %>
       <div class="container">
          <%= yield %>
       </div>
    <% end %>

    <!-- FOOTER -->
    <div class="container">
    	<%= render 'layouts/footer' %>
			<%= debug(params) if Rails.env.development? %> <!-- this is to not show debug information to users of a deployed app -->
    </div>
    <!--  <div id="fb-root"></div> -->
  </body>
</html>